import { Geist, Ubuntu} from "next/font/google";
import "./style/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"], 
  display: "swap",
});

export const metadata = {
  title: "Landrup Dans",
  description: "Generated by create next app",
};

// change description later 

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.variable} ${geistSans.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
